# Generated by Django 5.0.3 on 2024-04-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_webpage_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecord',
            name='favsport',
            field=models.CharField(default='chess', max_length=100),
        ),
    ]
